# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Harry's blog"
description: "My footsteps."

logo: "/assets/images/author.JPG"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cover.JPG"

name: 'Haruki AOKI'
author: 'Haruki AOKI'
author_image: "/assets/images/author.JPG"

paginate:	5

url: harry-arbrebleu.github.io
baseurl: /blog
twitter_handle: '@harry_arbrebleu'

social:
  - icon:	twitter
    url:	https://twitter.com/harry_arbrebleu
    desc: Follow me on twitter
    share_url: https://twitter.com/harry_arbrebleu
    share_title: ?text=
  - icon:	github
    url:	https://github.com/harry-arbrebleu
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
